### ISSUE TITLE
Key binding conflict

### ISSUE THREAD

**Issue by DzInLa** [Xentro/FS-AutoLoaderExtended#1]
Hello Xentro,

Your LIZARD XT-2 mod on the MODHUB is awesome! 

I have been able to get the folding function to work when using your script in my "WIP" Multi-Trailer mod. I changed IMPLEMENT_EXTRA2 "X" key to IMPLEMENT_EXTRA3 "Y" key. 
To have use of the  trailerConfigurations "Z" key, I changed TOGGLE_TIPSIDE "U" key to WORKMODE_LEFT "Left Ctrl + U" keys. 
My knowledge of LUA scripting is very limited but the comments you left inside AutoLoaderExtended.lua helped alot.

DzInLa

**Comment by Xentro** [comment]
Hi, Thanks!

For foldable you can change the input button trough xml with the "foldInputButton" tag, "IMPLEMENT_EXTRA2" is the default one.

I will update the script to be able to change key bindings trough xml to make life simpler for you. 👍

**Comment by DzInLa** [comment]
That will be great, I'm just a rookie at xml mod scripting. Downloaded all the mods that GIANTS releases. Learning what they expect in order to put my mod on the MODHUB once it is done. See my WIP... [https://youtu.be/VAWVVEgKdBU](url)

**Comment by Xentro** [comment]
https://github.com/Xentro/FS-AutoLoaderExtended/commit/4e1dfd60302c1a9c5cf67c7de7ce136891a12912
Is for you.

This would be an example how the xml line would look for you
`<autoLoader useTensionBelts="true" maxUnloadDistance="7" allowBaleToSetTime="25" unloadTime="150" unloadButton="IMPLEMENT_EXTRA3" unloadSideButton="WORKMODE_LEFT">`

Video looks good! are you intending to make use of the auto unload feature too? I might look into hiding that button if not.

**Comment by DzInLa** [comment]
I have been sharing my progress in the EXPENDABLES MODDING Facebook Group. Someone asked if I was going to add Autoloader to my mod. My first attempt was with the xml script from the LIZARD 8 BALE TRAILER. It has the option in the store to buy the trailer with or without Autoloader activated. His script uses the same buttons as the GIANTS bale loaders. I could not figure out how to get the FOLDING function to work. The LIZARD 8 BALE TRAILER is similar to your bale loading in the LIZARD XT-2.  [https://youtu.be/P9T1BjmcpmI](url) I added a rear unload location.

**Comment by DzInLa** [comment]
I tried the script above with the original  AutoLoaderExtended.lua but it did not work.
Did I do something wrong or will you have a revised  AutoLoaderExtended.lua for your  LIZARD XT-2 mod.

**Comment by Xentro** [comment]
> I tried the script above with the original AutoLoaderExtended.lua but it did not work. Did I do something wrong or will you have a revised AutoLoaderExtended.lua for your LIZARD XT-2 mod.

You need to download the latest version of AutoLoaderExtended.lua from this page for the new xml to work.
You will always find the latest version of the script here first.

**Comment by DzInLa** [comment]
Thank-you
[https://youtu.be/_auwabsE2z4](url)

**Comment by DzInLa** [comment]
For the following line, are the checkSize values 50% of the collision size?

        <loadSpace type="roundBale125" nodeToChildren="roundBale125"  checkSize="0.66 0.66 1" />
        <loadSpace type="roundBale150" nodeToChildren="roundBale150"  checkSize="0.80 0.80 1" />
        <loadSpace type="roundBale180" nodeToChildren="roundBale180"  checkSize="1.05 1.05 1" />
        <loadSpace type="squareBale"   nodeToChildren="squareBale240" checkSize="0.78 0.73 1.5" />

**Comment by Xentro** [comment]
> For the following line, are the checkSize values 50% of the collision size?
> 
> ```
>     <loadSpace type="roundBale125" nodeToChildren="roundBale125"  checkSize="0.66 0.66 1" />
>     <loadSpace type="roundBale150" nodeToChildren="roundBale150"  checkSize="0.80 0.80 1" />
>     <loadSpace type="roundBale180" nodeToChildren="roundBale180"  checkSize="1.05 1.05 1" />
>     <loadSpace type="squareBale"   nodeToChildren="squareBale240" checkSize="0.78 0.73 1.5" />
> ```

That is for the "overlap" box which you can debug by entering the console command "gsVehicleDebug", by doing so you will see green "boxes" which represent the value for checkSize.
while your game is running you can change the xml and then use "gsVehicleReload" to see the change in game but bear in mind that the debug shape shown in green will change depending on which loadSpace is currently active so load one object and then changing the value is the way to go.
You do not want the box too big as that can make the next location register as taken (depends how the bale is positioned) and you dont want it too small as that can make collision of the bales collide, this is true for round bales as for square bales those are a little more forgiving on the size.

**Comment by DzInLa** [comment]
Thanks for the detailed answer! I'm adding in 220 square bales.
